<?php

namespace JournaleBundle\Repository;

/**
 * BaremeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaremeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbybareme($nbre ){
        $dql_query = $this->_em->createQuery("
    SELECT b.note as note  FROM JournaleBundle:Bareme b  
    WHERE 
        b.min <= '".$nbre."' AND
      b.max >= '".$nbre."' "

        );
        $chasses = $dql_query->getResult();
        $note=0;
        if($chasses!=null){
            $n=$chasses[0];
            $note=$n['note'];

        }
        return $note;

    }
}
