<?php

namespace JournaleBundle\Repository;

/**
 * ompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ompetitionRepository extends \Doctrine\ORM\EntityRepository
{
}
