<?php

namespace JournaleBundle\Repository;

/**
 * TrophyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrophyRepository extends \Doctrine\ORM\EntityRepository
{
}
