<?php

namespace ForumBundle\Repository;

/**
 * Question1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Question1Repository extends \Doctrine\ORM\EntityRepository
{
}
