<?php

namespace ForumBundle\Repository;

/**
 * removeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class removeRepository extends \Doctrine\ORM\EntityRepository
{
}
