<?php

namespace ForumBundle\Repository;

/**
 * UpvoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpvoteRepository extends \Doctrine\ORM\EntityRepository
{
}
