<?php

namespace chasseBundle\Repository;

/**
 * annimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class annimalRepository extends \Doctrine\ORM\EntityRepository
{
}
