<?php

namespace chasseBundle\Repository;

/**
 * lieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lieuRepository extends \Doctrine\ORM\EntityRepository
{
}
