<?php

namespace chasseBundle\Repository;

/**
 * ratingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ratingRepository extends \Doctrine\ORM\EntityRepository
{

    public function update($id){
        $qb = $this->getEntityManager()->createQuery("SELECT avg(r.star) FROM chasseBundle:rating r where r.saison=?1 ")
            ->setParameter(1, $id);
        return $qb->getResult();
    }
}
