<?php

namespace chasseBundle\Repository;

/**
 * saisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class saisonRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateSais($id,$rat){
        $qb = $this->getEntityManager()->createQuery("update chasseBundle:saison s set s.rating =?1 where s.id=?2 ")
            ->setParameters(array(1=>$rat[0],2=>$id));
        return $qb->getResult();
    }
}
